print('Введите кол-во часов:')
a = int(input())
print('Введите кол-во минут:')
b = int(input())
print('Введите кол-во секунд:')
c = int(input())
d = a*3600+b*60+c
c = float(d/120)
print('Кол-во градуссов:', c)